### ISSUE TITLE
Request for release of realme GT5 Pro vendor and kernel source code

### ISSUE THREAD

**Issue by cherinyy** [realme-kernel-opensource/realme_GT5-AndroidT-kernel-source#1]
Please release the realme GT5 Pro vendor and kernel source code.

**Comment by realme-kernel-opensource** [comment]
> Please release the realme GT5 Pro vendor and kernel source code.

Dear Customer,
We will release the kernel source of the realme GT5 Pro in this quarter, please be patient, thanks.

**Comment by cherinyy** [comment]
https://github.com/realme-kernel-opensource/realme_GT5pro-AndroidU-kernel-source

https://github.com/realme-kernel-opensource/realme_GT5pro-AndroidU-vendor-source
